### ISSUE TITLE
Uprava XML feedu pro Heureka

### ISSUE THREAD

**Issue by pufexi** [pufexi/gk#12]
Budeme pracovat s /modules/zbozi/FeedHeureka.php , modul skrze ktery se generuje XML pro Heureku a dalsi, spousti se zde: http://gourmetkava.cz/modules/zbozi/feeds.php?id_shop=1 a vysledek je zde: http://gourmetkava.cz/xml/Gourmet káva_zbozi_heureka.xml

jakesi ovladani ma tady v "Admin - Moduly - Zbozi", ale v tom se nehrabej uz, sedel jsem nad tim ted asi 5h a nic jsem z toho nevytlouk poradnyho, takze co udelame...

- do PRODUCTNAME potrebuji narvat obsah Katalog - Produkty - ...vyberes produkt ... nalevo zalozka vlastnosti, tam vytvoris vlastnost "heureka-nazev" a v te bude jiz NAZEV, co se bude vkladat do PRODUCTNAME 
- do CATEGORYTEXTpotrebuji narvat to same, jen to bude cerpat z heureka-kategorie

v DB se tyhle veci nachazi v ps_feature_lang - nazev promenne, v ps_feature_value_lang obsah, to cele je pres ID produktu v ps_feature_product, tj. ten FeedHeureka.php ma jiz to ID produktu, to najdes v te tabulce ps_feature_product, a k nemu najdes jiz hodnoty v tabulkach  ps_feature_value_lang, coz je obsah, prenasena promena co pujde do XML a ps_feature_lang je nazev te promenne

Kdyz uz to budes delat, tak to same udelej pro FeedSeznam.php, kde jde taky o PRODUCTNAME, CATEGORYTEXT, ale poooozor! bude se cerpat z jinych hodnot "zbozi-nazev", "zbozi-kategorie"

A naposled i z jedny vody na cisto pro Google polozku nazev jen priprav jako promenou a vic ji nepriradime (nemam to nastudovane, takze nevim cemu) a kategorie "google product category".

**Comment by jachymb** [comment]
Implementováno pro feed heureka. pro feed seznam prosím vytvoř ty kategorie a já to dodělám už snadno, když vím jak na to. (ID kategorií fixně v kódu)

**Comment by pufexi** [comment]
1) pouzivej tvoji verzi te slozky "zbozi", ja si s tim trochu hral :)
2) obecne vsechny ty parametry budou fungovat takhle, kde xxx je zbozi/heureka/google
a) pokud neni nic v xxx-nazev, tak vkladej do PRODUCTNAME to, co je v PRODUCT
b) pokud neni nic v xxx-kategorie, tak vkladej do CATEGORYTEXT nazev kategorie v e-shopu, tedy treba "Pražená KÁVA"
c) pokud nic neni v xxx-cpc, tak vubec nevkladej tag s CPC (plati pro Heureka a Zbozi, Google nema)
3) ID tech vlastnosti produktu, co jsem vytvoril na ostrym... 5=heureka-nazev, 6=heureka-kategorie, 7=heureka-cpc, 8=zbozi-nazev, 9=zbozi-kategorie, 10=zbozi-cpc, 11=google-nazev, 12=google-kategorie
4) nefunguje to <CATEGORYTEXT> ani nevim proc, myslenka je tam ve zdrojaku dobra, ale v ostrem mi to nic neukazuje, asi nejaka drobnost 
5) u Zbozi.cz jeste pridat obsah z zbozi-cpc, pokud nejaky je, tak vytvorit ty 2 tagy, pokud zadny neni, nevytvaret
<MAX_CPC_SEARCH>
<MAX_CPC>
6) Zbozi.cz pridat <EXTRA_MESSAGE>free_store_pickup   .... vzdycky
7) ITEM_ID u Heureka ci ID u Google obsahuje cislo $product['reference'], tj. nase cislo pod kterym vse uvidujeme
8) jen pro ujasneni: google-cpc neexistuje, google-nazev existuje, ale nepouziva se, tedy pouze vyplnuj google-kategorie

Tot vse :-)

**Comment by jachymb** [comment]
Z fb:

Jeste do toho Zbozi feedu prosim pridat
EAN <http://napoveda.seznam.cz/cz/zbozi/napoveda-pro-internetove-obchody/specifikace-xml/#EAN> 
MANUFACTURER <http://napoveda.seznam.cz/cz/zbozi/napoveda-pro-internetove-obchody/specifikace-xml/#MANUFACTURER> 

V heurece uz jsou, takze v podstate to jen implementuj i na Zbozi.

**Comment by jachymb** [comment]
Mělo by to snad být vše, projdi si ty výstupy, jestli jsem to pochopil správně.

**Comment by pufexi** [comment]
1) nepropisuji se upravy v kategorii a jmenu produktu viz prvni "Kostarika: Tarrazu, zrnková káva arabica HEUREKA" avsak v adminu mam "Káva Costa Rica Tarrazu, zrnková, 250 g"

2) Potreboval bych udelat nakonec s tema categoriema jinac:
1) (vychozi) Pražená káva , tj. kategorie co mame na e-shopu
2) namapovani, tj. primo ve zdrojaku klidne case podminku kam si vyplnim tu mapu "Pražená káva" = "kat. takova a makova"
3) informace v produktu

a ridilo by se to od 3 k 1, tj. je informace v produktu, dal neresit, neni k 2... normalne bych udelal tabulku case, nebo if ... ve zdrojacich a moc se s tim neparal

**Comment by pufexi** [comment]
4)u Feedu Zbozi.cz bude vsude:
<SHOP_DEPOTS>gou0001</SHOP_DEPOTS>
namisto
<SHOP_DEPOTS>dets2908</SHOP_DEPOTS>

**Comment by jachymb** [comment]
1) Zkoumal jsem to v DB a bylo to nějakou nekonzistencí nastavení jazyka té vlastnosti. Bere to jen hodnotu s id_lang=1, což je angličtina. V tomhle případě tam byla nějak divně jiná hodnota pro češtinu a angličtinu. Můžu eventuálně změnit na češtinu.

**Comment by jachymb** [comment]
2,4) implementováno.

Proměnná, v níž je ta mapa je $category_map. Když tam budeš něco měnit, je potřeba, aby se ty změny dostaly ke mě. Tj, mi hned řekni ať si stáhnu aktuální verzi. Jestli se to má dít častěji, bylo by více než vhodné založit nějaký sdílený repozitář.

**Comment by pufexi** [comment]
1) no tak to nastav at to bere z CJ a ne AJ a je to vyresene, ze se to nejak divne propisuje do AJ je sice pravda, ale stejne by jsi to mel brat z CJ verzi, coz se asi ted nedeje

**Comment by pufexi** [comment]
achjo, dyt tam je zas opravena sotva pulka a to to resime snad od patku.... nahral jsem tam ty soubory + vyplnil takze viz implementovat 1) vyse
2) Zbozi `<CATEGORYTEXT>Káva Costa Rica Tarrazu, zrnková, 250 g</CATEGORYTEXT>`, tam ma byt kategorie
3) `<SHOP_DEPOTS>dets2908</SHOP_DEPOTS>` , tady je porad to stary, ma byt gou0001

**Comment by pufexi** [comment]
tak kdyz uz tak poradne, tedy opravime i Google Feed
4) <g:availability>in stock</g:availability> napevno u vseho
5) zobrazovat pokud je vyplnen EAN do <g:gtin>3234567890126</g:gtin>
6) do Shipping `<g:shipping>` dat uplne pryc
7) <g:id>tddy123uk</g:id> sem reference, tedy nase cislo, kterym vsude znacime
8) <g:product_type>Pražená Káva</g:product_type> sem vzdy eshop kategorie
9) <title>Mens Pique Polo Shirt</title> at nakonec funguje jako jinde, tedy nacita se z vlastniosti produktu, pokud tam nic neni necha se vychozi, je to vlastnost 11

ufff snad vse

**Comment by jachymb** [comment]
2) Načelo to sice kategorii, ale dál to pracovalo s názvem, na localu jsem si nevšiml, protože jsem mezi prvním položkami neměl takovou, kde by pro Seznam byl vyplněný název a nebyla kategorie
3) nevím proč se to nezměnilo, měl jsem za to, že jsem to dělal
4)přidáno
5) ean13. Text v tagu je kód
6) odebráno
7) už to tak bylo
8) kategorie jako "Pražená KÁVA". Systém mapy jako u ostatních se nepoužívá
9) Změněno

Pozn. U seznamu a heureky je teď doslova "kat. takova a makova". Koukni na to v kódu, podle potřeby změň a dej mi vědět, ať si stáhnu aktuální verzi souborů.

**Comment by pufexi** [comment]
"1) no tak to nastav at to bere z CJ a ne AJ a je to vyresene, ze se to nejak divne propisuje do AJ je sice pravda, ale stejne by jsi to mel brat z CJ verzi, coz se asi ted nedeje"

tohle je opravene, tedy ze se to nacita z te ceske jazykove mutace misto AJ?

**Comment by pufexi** [comment]
<g:product_type>Pražená Káva</g:product_type> tady to je okej, zustava kategorie, co je na eshopu, ale v <g:google_product_category>prelozena kat.</g:google_product_category> at se pouziva pravidlo, co je v google-kategorie -> mapa -> web , tj. pokud je neco v produktu, tak to, pokud ne, hledam mapu, pokud neni mapa, pouziju web kategorii tj stejny jak product type

**Comment by pufexi** [comment]
!! ty kategorie jsem tam jiz mel vyplnene, takze sis mel stahnout aktualni, sorry, myslel jsem ze to je jasne, takze ted si to stahni, doplnil jsem do tech tvych zdrojaku!!

**Comment by jachymb** [comment]
soubory jsem si sthánul.
Už to bere id_lang=2, tj češtinu.
