### ISSUE TITLE
Oprava bugu v kosiku

### ISSUE THREAD

**Issue by pufexi** [pufexi/gk#14]
Objevil jsem bug v kosiku, staci proste nejdriv vybrat dopravce, napriklad Osobni odber Praha a az potom vypnit osobni udaje, po odeslani osobnich udaju automaticky skoci oznaceni dopravce na vychozi hodnotu, tj. v mem pripade Postu, ale platebni metoda se zobrazuje jakoze k puvodnimu Osobnimu odberu.

Takze nastane situace, kdy si clovek muze udelat objednavku dopravce Česka Pošta , platba Hotovost, coz nejde, protoze tam je jen Prevodem, Dobirka, BTC. 

Tenhle bug podobne funguje se zasilkovnou, kde si clovek vybere Zasilkovnu a pobocku, pak vyplni udaje, platbu... a vysledek je dopravce Ceska posta s uvednim adresy zasilkovny v zavorce. To celkem neres a nemusis chapat :D 

--> Oprava toho vseho je podle me jednoducha, lidi donutit respektovat poradi zadavani. Takze vsechny ty policka pro vyber dopravce budou input disabled, tj. zasedla a po stisknuti tlacitka Vlozit osobni udaje se odebere disabled a bude moc vybrat doprava a platba. Vsechno pres jquery.

**Comment by pufexi** [comment]
Mozna tak na uvod Prestashopu, vetsina sablon a frontend se nachazi v /themes/default/ , pripadne /modules/modul... osobne v upravach Presty funguji tak, ze si v Firefoxu naprilklad kliknu pravym na nejaky prvek a dam Inspect Element, coz mi najde kde ve zdrojaku je kod k tomu prvku a pak vetsinou hledam nejakou unikatni frazi jako nazev tridy, id tagu apod... nikoliv nazev tlacitka v CJ, protoze tyhle hodnoty jsou v jazykovych mutacich ne primo sablonach. Takze mam najity nejaky unikatni prvek a ten proste dam hledat skrze celej web v tech souborech, takze projedu vsechny zdrojaky webu, vetsinou mi vypadnou 2 rozumny soubory, omkrnu a pracuji. To hledani mi na Win trva tak 20s, takze zadna tragedie. A urcite je to lepsi nez se snazit nejak pochopit tu strukturu, ja uz ji chapu trochu, ale protoze v tom delam dyl.

Takze kdyz je tady rec o upravach kosiku, tak se bavime o themes/default/order-opc-new-account pro ty policka, kde se zadava jmeno adresa a je tam tlacitko pro vlozeni tech udaju, naopak vyber dopravcu je order-carrier.tpl , no a to asi tak staci co potrebujes, je mozny, ze se tam bude odkazovat na nejaky JS, tak to je v themes/default/js ci css, samotny PHPkovy veci na pozadi byvaji ve slozce /controlers/

**Comment by jachymb** [comment]
Trvalo mi to dost dlouho, tvůj návrh tak úplně nebyl možný, protože se to neustál refreshuje ajaxem, takže i když jsem ty tlačítka nastavil enabled, hned mi je to zas zablokovalo, ale zavedl jsem si proměnnou co určuje jestli už se to uložilo. Celkem banalita vlastně, ale ten systém je dost složitej, než se to všechno najde...

Nejsem si jistý, jestli to funguje správně pro mobile. Udělal jsem v mobile souborech analogické změny, zkoušel jsem to na emulátoru a OK, ale ruku do ohně bych za to nedal.

**Comment by pufexi** [comment]
Jak jsem psal mobilni web neres, je stejny jako webovy jen je tam JSko na menu jinac.

Jinac, ja myslim, ze to funguje, ale premyslim o tom dal, protoze kazda uprava tady v tom muze prinest zvyseni konverzniho pomeru (/nakupy/navstevnici) a o procento klidne, to je dost penez ve vysledku :-) 

Takze ja bych mozna navrhoval, kdyz uz jsi to rozlouskl, vubec ty platebni metody nezobrazovat, tj. skryt "class="delivery_options_address" -> display: none  a misto toho zobrazit zluty ramecek jak u bodu 3. , kde bude stat cervene: "V bodu 1. (nalevo) vyplňte prosím osobní údaje a stiskněte "Vložit osobní údaje k objednávce" a posléze si zde budete moci vybrat dopravce."

A btw zas si tam prehral nejaky upraveny soubory, ten web je je vyvoji neustale, takze proste nemuzes vychazet z toho, co mas v kompu. Tezko radit jak postupovat, ja si proste najdu co budu delat u sebe a pak stahnu soubory aktualni s kterymi pracuji, beztak jich nikdy neni vic jak 3-5, takze se to da. Prehral jsi order-carrier.tpl, protoze jsem tam mel vlozeny telefon. TAK SI STAHNI AKTUALNI.

**Comment by jachymb** [comment]
Udělal jsem to. Popravdě řečeno, je to trochu hack tím, že to dělá JS, ty tlačítka tam ze začátku probliknou, než je to přepíše touhle zprávou. (Naopak chvílema, když se aktualizuje shipmethod, třeba při změně hodnoty, tak na chvíli problikne jako disabled a pak ho JS zas povolí.) Ale myslím, že by to v normálním provozu nemělo vůbec vadit.

**Comment by pufexi** [comment]
vubec se neprojevil, asi jsi zapomnel nahrat ne? ja to mam porad jak predtim, tedy disabled option namisto te vety v jinem divu

**Comment by pufexi** [comment]
Takze pokud se to tyka platby, tak ta uz tam mela moje zneni textu nejakou dobu :-) Coz me trochu zarazi, ze jsi to delal, hlavne aby to fungovalo no :-) Takze o to moc nejde a ano problikne... ale me slo o to udelat tohle same i s dopravcema, abychom jasne ty lidi nasmerovali na bod 1 a nebloudili po zasedlych options u 2 kroku. 

Takze bych udelal proste ze tam bude videt jen vkladani osobnich informaci s tlacitkem a krok 2 a 3 bude mit jen upozorneni jak ma nyni krok 3.

2. krok tam bude veta "Vyplňte osobní údaje v kroku 1. (nalevo) a stiskněte „Vložit osobní údaje k objednávce“. Možnosti dopravy se vám zobrazí po zadání kontaktních údajů v závislosti na vaší adrese."

3. krok tam bude věta "Vyplňte osobní údaje v kroku 1. (nalevo) a stiskněte „Vložit osobní údaje k objednávce“. Možnosti platby se vám zobrazí po zadání kontaktních údajů v závislosti na vaší adrese a dopravci."

Krok 2. a 3. se samozrejme odblokuje najednou.

**Comment by jachymb** [comment]
Již opraveno... tak asi je to k uzavření, nebo ještě něco?
