### ISSUE TITLE
Zalohovani OK?

### ISSUE THREAD

**Issue by pufexi** [pufexi/gk#15]
http://www.gourmetkava.cz/backupdb/backuper.php haze to nejaky warningy, myslis ze je to OK?

**Comment by pufexi** [comment]
nahodil jsem tam novou verzi, ale stejne to hazi warningy

**Comment by jachymb** [comment]
Koukal jsem na to, je to v pohodě. Ten dotaz co vybírá ty tabulky narozdíl od SHOW FULL TABLES vrátí třeba i tabulky typu SYSTEM VIEW, které nemusíme exportovat a na nich to hází ten warning. Pozměnil jsem to, že to vypisuje že dotyčnou tabulku ignoruje, tedy kdyby se tam objevil warning, tak je to něčím jiným.
