### ISSUE TITLE
"Účet s tímto e-mailem je již zaregistrován, příhlaste se prosím v boxu napravo."

### ISSUE THREAD

**Issue by pufexi** [pufexi/gk#16]
Ten kosik je celkem osekanej, puvodni prestahop, je totiz mega slozitej a ma tam moznost registrace , registrace zaroven s objednavkou a objednavku bez registrace, takze jsem to vsechno odstrelil a jedem vsechno skrze neregistrovanou objednavku, tj vytvari to zakazniky ve skupine Host, kteri by meli mit moznost udelat znovu objednavku se stejnym emailem, narozdil kdyby byli zaregistrovany, tak jim to napise logicky at se prihlasi. Nicmene se zda, ze minimalne u emailu skodik@gmail.com to hlasi take, at se prihlasim. Z toho usuzuji, ze cely tenhle kontrolni mechanismus bych rad deaktivoval, ne uplne smazal, ale nejak zakomentoval.

Tj. nejak udelej at skodik@gmail.com projde, protoze nemuzu vyloucit, ze se to nedeje i vic zakaznikum, ackoliv si na to tedy nikdo nestezoval zatim. Budou to resit nejaka PHPcka na pozadi, podle me neco jako controllers/OrderOpcController.php a nicmen vyjit muzes z tpl sablony pro opc-order v themes/default.

**Comment by jachymb** [comment]
Změněno. Teď to normálně uloží. 

Týkalo se to 
```override/controllers/front/AuthController.php```

**Comment by pufexi** [comment]
Supr!

**Comment by pufexi** [comment]
donahraji si na ostatni weby
