### ISSUE TITLE
Dvojta cisla objednavek!!

### ISSUE THREAD

**Issue by pufexi** [pufexi/gk#18]
Mam tady "mega" prusvich, mam tu dvakrat stejna cisla objednavek viz 2015400291, 2015400290 celkem 3x dokonce, nechapu jak se to mohlo stat, 

1) potrebuji to opravit
2) potrebuji zjistit, ktere jsou duplicitni v ramci GourmetKavy a pokud jich bude hodne, tak asi i navrhnout script, co to precisluje, aby to byla opet casova posoupnost

Jen upozorneni v ramci 1 firmy je 1 casova rada, kde jsou unikatni, v ramci vic firem tedy mohou byt stejne.

**Comment by jachymb** [comment]
Opraveno. Kolega na prtgrade to může opravit skiptem v nastavení a následným nastavením unique na invoiceid.
 Pozor: Zkontrolovat, zda tento dotaz vrátí prázdný výsledek:
```SELECT * FROM `orders` WHERE shipstate!=1 and pickstate!=1;```
Pokud není prázdný (u nás nebyl, asi pozůstatky z doby kdy se vyzvednutí zavádělo, tak zařídit, aby byl, otázka ruční úpravy snad jen pár požadavků v db.

**Comment by jachymb** [comment]
Přečíslováno novým způsobem
