### ISSUE TITLE
Zmizela mi moznost generovat faktury v detailu objednavky

### ISSUE THREAD

**Issue by pufexi** [pufexi/gk#19]
rozklikni si a uvidis, je to tim, ze se ty tlacitka zobrazuji pouze, kdyz je zasilka odeslana, ale ne kdyz uz je i dorucena, at se zobrazuji na oba stavy

**Comment by jachymb** [comment]
Opraveno... Kdyžtak prosím pro přehlednost multiorder issues do https://github.com/pufexi/multiorder/milestones
