### ISSUE TITLE
Nefunkcni sablona + vystaveni dle korenove kat

### ISSUE THREAD

**Issue by pufexi** [pufexi/gk#25]
1) nefunguje mi sablona, ted jsem tam nahral toto: http://aukro.cz/show_item.php?item=5603395543 ani jednou se nenahrala sablona, mam tam takovych veci vic

2) udelej at se to tedy urcuje ten eshop i podle korenove kategorie tedy pufexicz, ja ted zkousel ty BCAA tablety, meli tam nastaveno pufexicz, proto se nevystavovali, nastavil jsem jim BCAA a jde to, takze to udelej at to funguje i podle toho pufexicz

**Comment by jachymb** [comment]
2) Implementováno (plošně, nejen pro šablony), pufexi i gk 

1) Momentálně to např neumí určit kategorii pro např "250g kofein bezvodý" (viz ve frontě položky s "Chybí šablona!" pro další příklady.)
Důvod: 

Id produktu = 101. id_category_default=62. id_parent = 53. Tento rodič je "cistykofeincz", což není ani GK ani pufexi. 
V rozhraní se zdá, že je tam zaškrtnuto E-SHOP, což přesně nechápu proč, nicméně v DB to je tak jak jsem popsal. Řekl bych, že řešení asi budeš líp vědět ty. Nejsou ta pole zakázaná nebo tak něco?

**Comment by pufexi** [comment]
Opet se to vystavilo bez sablony http://aukro.cz/show_item.php?item=5609128340 viz dnes jsem to pustil

**Comment by pufexi** [comment]
vypada to funkcni
