### ISSUE TITLE
1 zboží ve více sekcích na Aukru

### ISSUE THREAD

**Issue by pufexi** [pufexi/gk#26]
Ten AukroKonektor to vypada jako kdyby umoznoval vystavovani produktu ve vice sekcich na aukru. Cele to totiz funguje tak, ze aby vedel do jake sekci na Aukro vystavit jaky produkt, tak mu sdelim, ze sekce treba Moka konvice u nas v eshopu obsahuje zbozi, ktere je na Aukru v Kuchynske vybaveni, napriklad. Tohle se nastavuje v "Aukro-Nastaveni-Mapovaní kategoriíí", ale tam lze pro 1 Prestashop sekci nastavit vice sekci Aukro, bylo by mozne, aby to tedy i v praxi tak probehlo, tedy, ze pokud bude mit 1 sekce v preste vic sekci na Aukru, tak se to do kazde na aukru vystavi? Jak moc to odhadujes narocne?

Ted se tak nedeje, protoze treba na Pufexi mam nastaveno to viz nize, ale propisuje  se to pouze do jedne, clovek by rekne, ze to vybere pokazdy stejnou, ale paradoxne, je to nejak na stridacku, ted jsem tu hodne vystavoval a rusil a jednou se to vystavilo do te a podruhy do te druhe, ale nikdy ne do obou naraz :-)
Aukro-Nastaveni-Mapovaní kategoriíí
#27	pufexicz » L-karnitin	Lékárna a Zdraví » Hubnutí » Přípravky na hubnutí  
#28	pufexicz » L-karnitin	Sport a Turistika » Sportovní výživa » Carnitinové produkty

**Comment by jachymb** [comment]
Implentováno. Zdá se mi, že to funguje OK, vystavilo se tak např: http://aukro.cz/ShowItem2.php?item=5645848564 a http://aukro.cz/ShowItem2.php?item=5645848522 do dvou kategorií týž produkt. 

Ve "Vystavit zboží" se zobrazují všechny kategorie u jednoho produktu. Po přidání do fronty (resp. nabídek) se to už rozděluje na jednotlivé položky, které jsou stejné až na kategorii.

**Comment by pufexi** [comment]
funguje, diky!
