### ISSUE TITLE
"Tato adresa neni platna"

### ISSUE THREAD

**Issue by pufexi** [pufexi/gk#31]
Na gourmetkava, blbne kosik, je tam nejaka dalsi nadbytecna kontrola patrne. Udelam objednavku na email "info@pufexi.com" jmeno: fdsa prijmeni: fdsad a nejaky blaboly do adresy, obj probehne OK, ale kdyz chci pak udelat hned 2. ci 3. tak to napise pri Vlozit osobni udaje... "Tato adresa neni platna" a cloveka to nepusti dal, ani kdyz ruzne upravuje vsechno mozny.

Myslel jsem si, ze to asi snad dela jen me, ale dnes mi nekdo psal, ze mu to nejde take a obcas nekomu neco nejde, ten kosik to je tragedie no. Takze takovych lidi je asi vic a treba se neozvou zejo.

Takze napise to to, co vidis na screnshotu, od hledani tehle hlasky bych se odrazil. Po stisknuti OK, jsem v tom formulari, muzu vybrat Dopravu a v sekci 3 Platby je "Chyba: vyberte adresu".

<b>Cim by to mohlo byt?</b>
Ten eshop puvodne pracuje jak asi uz i vis v rezimu Host / Zakaznicky ucet (tj. registrace atd..), ja/my jsme tu moznost Host uplne ze zdrojaku vystipali a vlastne pres JS se pri vstupu do kosiku jakoby stiskne tlacitko Host. No proc to pisu, vim, ze v registrovanem uctu je moznost vyberu adres, tj. ze mas ulozenych nekolik adres a ty nejakou vyberes. Mam pocit, ze tohle s tim ma nejakou spojitost, tj. ze ta hlaska vlastne reaguje na neco ve stylu, ze neni vybrana spravna adresa z nejakeho asi selectboxu, ktery kazdopadne neni.
Jako prvne bych se s tim asi moc neparal a zkusil proste jednoduse odstranit tenhle kontrolni mechanismus, co k te hlasce vede.

Pochybuji, ze to nasimulujes, to vubec nevim jak toho dosahnout, ale pokud mas nejakou vzdalenou plochu treba staci TeamViewer muzu te pustit i na muj PC at to vidis, a muzes to klidne zkusit nejak ladit. Pocitam s tim, ze vyreseni tohodle ukolu muze stat nejaky cas.

![193a5b46-7513-11e5-9271-c09d07a4251d](https://cloud.githubusercontent.com/assets/10209182/10610310/91a74c70-7747-11e5-8e6e-12bfff8139da.jpg)

**Comment by jachymb** [comment]
Zjištění: Na řádku 185 v controllers/front/OrderOpcController.php si myslí, že $address_invoice->deleted == 1, pročež projde podmínka na chybu. Zatím nevím proč se to přesně děje.

**Comment by pufexi** [comment]
tak zkus at to nekontroluje, no... sak vis co mas delat :-)

**Comment by jachymb** [comment]
Tak odebral jsem tu kontrolu na adresu "deleted" u tý chyby a přestalo jí to dělat. Objednávka se udělala a importovala do MO. Nicméně to "deleted" tam v databázi skutečně pořád je a mohlo by to potenciálně začít strašit někde jinde. Pořád nevím, proč se to děje, takže jsme jen odstranili projev chyby, nikoliv příčinu.

**Comment by pufexi** [comment]
Me to porad hlasi to chyba vyberte adresu, takze to asi ten mechanismus stale funguje. Jinac podle me to funguje nejak tak, ze ja se dostanu do kosiku a mam predvyplnene udaje, nevim co mi to presne dela asi nejaky plugin, to je celkem jedno. Ale vysledek je toto. Muzem to beta testovat asi leda na vzdaleny plose, pouzivam TeamViewer.

**Comment by jachymb** [comment]
Moc nevím, jak to myslíš, ale kdyžtak se nějak dohodnem. Teď jsem to zkoušel s info@pufexi.cz a prošlo to. Předtím ne.

**Comment by jachymb** [comment]
Aha, tak to "Chyba: vyberte adresu" je další projev tý chyby, což ilustruje to, že jsme odstranili jen symptom.

**Comment by jachymb** [comment]
Pošteloval jsem tam několik hidden inputů, který se týkaly uschovávání informace o existující adrese uživatele, aby to vypadalo, jakože ještě neexistuje. Zdá se mi, že to tentokrát zabralo. Tj, tu chybu s "Vyberte adresu" se mi předtím podařilo reprodukovat a teď už ne.

**Comment by pufexi** [comment]
super parada!
