### ISSUE TITLE
Aukro modul -chybna materska kat.

### ISSUE THREAD

**Issue by pufexi** [pufexi/gk#35]
Stala se takova vec, zavedl jsem do GK podkategorie a zacal blbnout Aukro modul, produkty, ktere maji jako vychozi kategorii nejakou kategorii 2 urovne, napriklad jakakoliv kava, kde mam vychozi kategorii Zrnkova kava, se nakonec nezobrazi ve vypisu admin - Aukro - Vystavit zbozi, je to dle meho nazoru tim, ze se tam zobrazuji jen ty, co maji nadrazenou kategorii E-SHOP (toto jsme si umele stanovili), ale u techto podkategorii se zobrazi Nadrazena kategorie Prazena KAVA a az ta samotna ma E-SHOP, takze musime proste kouknout jeste o uroven vys, aby to zaclo fungovat, muzes to opravit?

NEPOUZIVEJ NYNI GIT, GK JE DOST PREDELANA, TOHLE MUSIM NEJAK SYNCNOUT ZNOVA, ALE TYHLE UPRAVY O KTERYCH MLUVIME JSOU V MODULES/aukroconnector

**Comment by jachymb** [comment]
Myslím že opraveno. Předtím se zobrazilo 359 výsledků, teď 490. Na první stránce přibyly hlavně kávy, což asi teda taky odpovídá. Udělal jsem ekvivalentní úpravu na všech místech, kde to nějak pracuje se zbožím, nejen ve "vystavit zboží". Podívej se na to ještě, jestli to funguje dle očekávání a jinak teda doufám že se tím třeba nerozjebalo něco někde vedle, to můžu těžko otestovat a ten modul mi přijde poměrně "chatrnej" :/ Kdybys našel něco podezřelého, tak hlásit

**Comment by pufexi** [comment]
z nejakyho duvodu to ted zas nenacita vubec sablonu, u niceho, takze se tam nic neprodava :/

**Comment by jachymb** [comment]
Fronta už má šablony pro další 1 úroveň vnoření. Když budeš chtít ještě další, musíš říct. Udělat obecnou dědičnost v čistým sql neumím.

**Comment by pufexi** [comment]
funguje
