### ISSUE TITLE
auto promaz slozky www.gourmetkava.cz/cam/

### ISSUE THREAD

**Issue by pufexi** [pufexi/gk#36]
Chtel bych cron skript, co bude ve slozce cam, napriklad cron.php, ktery je uplne mimo web a proste to bude PHPko samostatne, co smaze soubory starsi 72h / 3 dny, skript budu poustet kazdy den o pulnoci, tedy bude se poustet napriklad na prelomu nedele/pondeli a chci aby tam nechal soubory za patek, sobotu, nedeli a smazal vse predtim.

soubory maji tento tvar:
000DC5D385CA(gk-cam)_1_20160322085749_106616.jpg
tj. vidis tam datum 2016 / 03 / 22 ...8h 57min 49s

!!!! DULEZITE VUBEC TED NEPOUZIVEJ GIT, GK NYNI NEMA FTP STEJNE S GIT, NICMENE PRO TENTO UKOL TO VUBEC NEVADI, PROSTE NAPROGRAMUJ TO PHPKO A JA SI HO MANUALNE STAHNU ;-) !!! GIT VYRESIM BRZY, TO JE TAKOVEJ MUJ PRUSVICH :-)

**Comment by jachymb** [comment]
na gk máš skript camclean.php. Když se podíváš dovnitř, jde tam snadno nastavit doba.
