### ISSUE TITLE
modul Zbozi mensi bug

### ISSUE THREAD

**Issue by pufexi** [pufexi/gk#37]
(stahni si aktualni zdrojaky z /modules/zbozi)!!

skrze http://www.gourmetkava.cz/modules/zbozi/feeds.php generuji http://gourmetkava.cz/xml/zbozi_heureka.xml a ty skripty jsou v FeeeXXX.php, kde se to tyka Seznamu, Heurek a tak, takze 4 php. 

No a k veci, u zbozi, kde se automaticky voli kategorie dle nazvu kategori a nikoliv dle toho, co je v detailu produktu napriklad <CATEGORYTEXT>Čistící prostředkyFrench press Bialetti</CATEGORYTEXT> , vsude je to Cistici prostredky, ale ma byt jen French press.... deje se to pokud to nenajde v te parovaci tabulce spravnou kategorii a ani neni uvedena u produktu konkretne.

prosim o opravu.

**Comment by jachymb** [comment]
Změněno, bere se jen "nejnižší" kategorie. Moc mi není jasné odkud se tam to "Čistící prostředky" vzalo, ale to asi budeš vědět ty

**Comment by pufexi** [comment]
to mi prave vubec jasny neni no... takze to je ta potiz, takovy nazev kategorie neni

**Comment by jachymb** [comment]
Ale je, si zkus `select * from ps_category_lang where name LIKE 'Čistící prostředky'` - kategorie 76 pro shop GourmetKáva. Je to podkategorie E-SHOP. Jsou v ní produkty s GKid 438,439,440,441,479,502,503,506.
Mám to nějak dál řešit nebo to už dělá to co chceš?

**Comment by pufexi** [comment]
nejak se to samo vyresilo :)
