### ISSUE TITLE
Divny stavy zasob?

### ISSUE THREAD

**Issue by pufexi** [pufexi/gk#39]
Deje se takova divna vec, kdyz dam Admin - Produkty, tak vidim u Brazílie: Santos a i jinych kav zaporny stavy zasob, nicmene po rozkliknuti a prepnuti obchodu do Microsites, abych mohl zobrazit stavy, tam vidim spravny cisla z MO... v zasade to asi moc nechci resit, ale muzes tam nastavit nekam treba 99999 u tech kav.

Vlastne to cele resim, protoze tohle cislo se pak propisuje do slozenych produktu jako "Arabica z celého světa - 1kg, výhodné balení!" ci "Francouzský balíček" apod... kde se pak nastavi zaporny stav. Jde jen o ty kavy a ty mame stejne skoro porad skladem, takze i kdyby nahodou nebyli a prodal se jeden z tech balicku vyse, tak to neni katastrofa, proto bych to vyresil tim, ze se nastavi 99999 nez resit proc to tam ukazuje zaporne cislo, kdyz to zaporne neni.

**Comment by pufexi** [comment]
![screen](https://cloud.githubusercontent.com/assets/10209182/15293373/f1fd22a4-1b87-11e6-8bab-a92f4c8b514b.png)

**Comment by jachymb** [comment]
Není to nijak záhadné. Nahrála se tam čísla z MO (ber v potaz přepočet hmotností a rezervované kusy), které byly v MO záporné. Nastavil jsem v MO u káv s nenulovou (i zápornou) zásobou zásobu na 999999 a skriptem jsem aktualizoval do GK. Teď už tam záporná čísla nejsou.
