### ISSUE TITLE
Sekce Novinky

### ISSUE THREAD

**Issue by pufexi** [pufexi/gk#8]
Je to vlastne obycejna stranka, ale delam z toho tak trochu blog, takze bych chtel aby zde (http://www.gourmetkava.cz/blog-23k) byli i obrazky a datum nejak.
1) obrazky bych docilil tak, ze se tam bude vkladat obrazek http://gourmetkava.cz/img/cms/blog/123.jpg , kde 123 bude ID toho clanku, ten obrazek bude mit vetsi velikost patrne, takze ho browser zmensi.
2) datum bych nacital z klicovych slov, bude tam v podobe "datum:22.2.2003", ten se da do vypisu clanku pod nadpis i pod nadpis tady do clanku, pripadne mi sdel promenou a ja ho do clanku nejak umistim

**Comment by pufexi** [comment]
not ready yet

**Comment by pufexi** [comment]
Asi bych to zobecnil, ze to bude delat ve vsech sekcich nejen Novinky, protoze dost lidi klika v menu na ty hlavni tlacitka http://www.gourmetkava.cz/pro-firmy-5k a nepocka na rozvinuti toho seznamu. Jinac velikost toho obrazku by byla 120x120. Pokud zadny takovy obrazek nebude, tak se to zobrazi jako dnes bez.

Obrazky budou vsechny v /img/cms/nahledy/

**Comment by pufexi** [comment]
themes/default/cms.tpl radek 107

**Comment by jachymb** [comment]
Implementováno. Funguje to obecně pro všechny sekce. Obrázky se berou vždy z /img/cms/nahledy/ (i pro blog, kdyžtak nakopírovat)
Obrázek má velikost 80px, při větší se to rozsypávalo (u těch co mají delší doprovodný text, ne vždy). Je možné, že i při této velikosti se to rozsype když někde bude dlouhý text, text s dlouhými slovy. Tak asi radši vždy zkontrolovat, eventuelně v themes/default/cms.tpl zmenšit velikost nebo pozměnit text.

Vzhed datumu definován v themes/default/css/global.css Datum teoreticky funguje i pro ostatní sekce. U samotného článku není, moc jsem nevěděl kam ho tam přilepit, kdyžtak řekni a dodělám.
